(in-package :sdl3)

(defun test ()
  (dotimes (i (get-num-render-drivers))
    (format t "~a~%" (get-render-driver i)))
  (when (not (init (logior +init-audio+ +init-video+)))
    (format t "failed ~a~%" (get-error))
    (return-from test 'failed))
  (multiple-value-bind (rst whandle rhandle)
      (create-windows-and-renderer "test" 1024 1024)
    (format t "system theme ~a~%" (get-system-theme))
    (format t "video drivers ~a~%" (get-num-video-drivers))
    (format t "current video drivers ~a~%" (get-current-video-driver))
    (when (not rst)
      (cffi:foreign-free whandle)
      (cffi:foreign-free rhandle)
      (format t "failed ~a~%" (get-error))
      (return-from test 'failed))
    (delay 1000)
    (quit)
    (cffi:foreign-free whandle)
    (cffi:foreign-free rhandle)))
