(in-package :sdl3)

(cffi:defctype haptic-id :uint32)

(deflsp-type haptic-direction
  (type :uint8)
  (dir :int32 :count 3))

(deflsp-type haptic-constant
  (type :uint16)
  (direction (:struct haptic-direction))
  (length :uint32)
  (delay :uint16)
  (button :uint16)
  (interval :uint16)
  (level :int16)
  (attack-length :int16)
  (attack-level :int16)
  (fade-length :int16)
  (fade-level :int16))

(deflsp-type haptic-periodic
  (type :uint16)
  (direction (:struct haptic-direction))
  (length :uint32)
  (delay :uint16)
  (button :uint16)
  (interval :uint16)
  (period :uint16)
  (magnitude :int16)
  (offset :int16)
  (phase :uint16)
  (attack-length :int16)
  (attack-level :int16)
  (fade-length :int16)
  (fade-level :int16))

(deflsp-type haptic-condition
  (type :uint16)
  (direction (:struct haptic-direction))
  (length :uint32)
  (delay :uint16)
  (button :uint16)
  (interval :uint16)
  (right-sat :uint16 :count 3)
  (left-sat :uint16 :count 3)
  (right-coeff :int16 :count 3)
  (left-coeff :int16 :count 3)
  (deadband :uint16 :count 3)
  (center :int16 :count 3))

(deflsp-type haptic-ramp
  (type :uint16)
  (direction (:struct haptic-direction))
  (length :uint32)
  (delay :uint16)
  (button :uint16)
  (interval :uint16)
  (start :int16)
  (end :int16)
  (attack-length :int16)
  (attack-level :int16)
  (fade-length :int16)
  (fade-level :int16))

(deflsp-type haptic-left-right
  (type :uint16)
  (length :uint32)
  (large-magnitude :uint16)
  (small-magnitude :uint16))

(deflsp-type haptic-custom
  (type :uint16)
  (direction (:struct haptic-direction))
  (length :uint32)
  (delay :uint16)
  (button :uint16)
  (interval :uint16)
  (channels :uint8)
  (period :uint16)
  (samples :uint16)
  (data (:pointer :uint16))
  (attack-length :int16)
  (attack-level :int16)
  (fade-length :int16)
  (fade-level :int16))

(defcunion haptic-effect
  (type :uint16)
  (constant (:struct haptic-constant))
  (periodic (:struct haptic-periodic))
  (condition (:struct haptic-condition))
  (ramp (:struct haptic-ramp))
  (leftright (:struct haptic-left-right))
  (custom (:struct haptic-custom)))
